name = "GC Website Functions Client"
prefix = "gc_websiteFunctionsClient"
author = "W-Cephei"
files = [
    "mod.cpp"
]

key_name = "{{prefix}}_{{version}}"


releasebuild = [
    "@zip gc_websiteFunctionsClient_{{semver.major}}.{{semver.minor}}.{{semver.patch}}.{{semver.build}}"
]

