name = "Gruppe Adler Admin Messages"
prefix = "gc_websiteFunctionsClient"
author = "McDiod, Salbei"
files = [
    "mod.cpp"
]

key_name = "{{prefix}}_{{version}}"


releasebuild = [
    "@zip gc_websiteFunctionsClient_{{semver.major}}.{{semver.minor}}.{{semver.patch}}.{{semver.build}}"
]

